Repository AY2223S2-CS2103-W17-3/tp, pull requests merged in 2023-04, with the labels that each got.

#162 Resolve complains about user guide
  docs/UserGuide.md
Labels: docs

#163 Fixed overlap in time bug
  src/main/java/ezschedule/logic/commands/EditCommand.java
  src/main/java/ezschedule/model/event/Event.java
  src/main/java/ezschedule/model/event/Time.java
  src/main/java/ezschedule/model/event/UniqueEventList.java
  src/test/java/ezschedule/logic/commands/AddCommandTest.java
  src/test/java/ezschedule/model/event/EventTest.java
Labels: bugfix

#164 Fix wrong calendar event name bug
  docs/DeveloperGuide.md
  src/main/java/ezschedule/model/event/Event.java
  src/main/java/ezschedule/ui/Calendar.java
  src/main/java/ezschedule/ui/CalendarBox.java
Labels: bugfix

#165 Improve Recur parameter description in UG
  docs/UserGuide.md
Labels: docs

#166 Add appropriate checks for RecurCommand
  src/main/java/ezschedule/logic/commands/RecurCommand.java
  src/main/java/ezschedule/model/event/RecurFactor.java
Labels: bug, type.Enhancement

#171 User Guide: "High level" indication for required format for date and time.
  docs/UserGuide.md
Labels: docs

#172 Enhance SchedulerParser
  src/main/java/ezschedule/logic/parser/SchedulerParser.java
  src/test/java/ezschedule/logic/parser/SchedulerParserTest.java
Labels: bugfix

#170 Undo feature: fix wrong message shown, exception thrown when...
  src/main/java/ezschedule/MainApp.java
  src/main/java/ezschedule/logic/commands/AddCommand.java
  src/main/java/ezschedule/logic/commands/DeleteCommand.java
  src/main/java/ezschedule/logic/commands/EditCommand.java
  src/main/java/ezschedule/logic/commands/RecurCommand.java
  src/main/java/ezschedule/logic/commands/UndoCommand.java
  src/main/java/ezschedule/logic/parser/SchedulerParser.java
  src/main/java/ezschedule/model/Model.java
  src/main/java/ezschedule/model/ModelManager.java
  src/test/java/ezschedule/logic/commands/AddCommandTest.java
Labels: bugfix

#173 Update RecurCommand
  src/main/java/ezschedule/logic/commands/RecurCommand.java
  src/main/java/ezschedule/logic/parser/RecurCommandParser.java
Labels: bugfix

#178 Update RecurCommand
  src/main/java/ezschedule/logic/commands/RecurCommand.java
Labels: bugfix

#183 Improve RecurCommand error message
  src/main/java/ezschedule/logic/commands/RecurCommand.java
Labels: type.Enhancement

#182 Add test cases for DeleteCommand related classes
  src/main/java/ezschedule/logic/commands/DeleteCommand.java
  src/main/java/ezschedule/logic/parser/DeleteCommandParser.java
  src/test/java/ezschedule/logic/commands/DeleteCommandTest.java
  src/test/java/ezschedule/logic/parser/DeleteCommandParserTest.java
Labels: type.Tests

#181 Add test cases for EditCommand related classes
  src/test/java/ezschedule/logic/commands/EditCommandTest.java
  src/test/java/ezschedule/logic/parser/AddCommandParserTest.java
  src/test/java/ezschedule/logic/parser/EditCommandParserTest.java
Labels: type.Tests

#177 Tests for ShowNextCommand, chronological sort
  src/main/java/ezschedule/logic/parser/ShowNextCommandParser.java
  src/main/java/ezschedule/model/event/UniqueEventList.java
  src/test/java/ezschedule/logic/commands/CommandTestUtil.java
  src/test/java/ezschedule/logic/commands/ShowNextCommandTest.java
  src/test/java/ezschedule/logic/parser/ShowNextCommandParserTest.java
  src/test/java/ezschedule/model/SchedulerTest.java
Labels: type.Tests

#188 Add test cases for equals method in ShowNextCommandTest
  src/test/java/ezschedule/logic/commands/ShowNextCommandTest.java
Labels: type.Tests

#186 Add test cases for FindCommand related classes
  src/test/java/ezschedule/logic/commands/FindCommandTest.java
  src/test/java/ezschedule/logic/parser/FindCommandParserTest.java
Labels: type.Tests

#189 Add InvalidDateException to CommandBox
  src/main/java/ezschedule/ui/CommandBox.java
Labels: bugfix

#190 Add test cases for Event class
  src/test/java/ezschedule/logic/commands/CommandTestUtil.java
  src/test/java/ezschedule/model/event/EventTest.java
Labels: type.Tests

#191 Remove fxml start up warning
  src/main/resources/view/Calendar.fxml
  src/main/resources/view/CalendarBox.fxml
  src/main/resources/view/EventListCard.fxml
  src/main/resources/view/EventListPanel.fxml
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/ShowNextCard.fxml
  src/main/resources/view/ShowNextPanel.fxml
Labels: bugfix

#195 Add test cases for Name and modified equals test case in other class
  src/test/java/ezschedule/logic/commands/AddCommandTest.java
  src/test/java/ezschedule/logic/commands/DeleteCommandTest.java
  src/test/java/ezschedule/logic/commands/EditCommandTest.java
  src/test/java/ezschedule/logic/commands/FindCommandTest.java
  src/test/java/ezschedule/logic/commands/ShowNextCommandTest.java
  src/test/java/ezschedule/model/event/EventTest.java
  src/test/java/ezschedule/model/event/NameTest.java
Labels: type.Tests

#194 Add test cases for Date class
  src/test/java/ezschedule/model/event/DateTest.java
  src/test/java/ezschedule/model/event/EventTest.java
Labels: type.Tests

#187 User Guide: Add warning to tell user not to modify storage files
  docs/UserGuide.md
Labels: docs

#196 Add test cases for Time
  src/test/java/ezschedule/model/event/TimeTest.java
Labels: type.Tests

#202 Test UpcomingEventPredicate constructor and equals()
  src/main/java/ezschedule/model/event/UpcomingEventPredicate.java
  src/test/java/ezschedule/model/event/UpcomingEventPredicateTest.java
Labels: type.Tests

#198 Add test cases for Predicates and UniqueEventList classes
  src/test/java/ezschedule/model/event/EventContainsKeywordsPredicateTest.java
  src/test/java/ezschedule/model/event/EventMatchesDatePredicateTest.java
  src/test/java/ezschedule/model/event/EventMatchesKeywordsAndDatePredicateTest.java
  src/test/java/ezschedule/model/event/UniqueEventListTest.java
Labels: type.Tests

#200 Add test cases for LogicManager, ModelManager and AppParameters
  src/main/java/ezschedule/logic/commands/FindCommand.java
  src/test/java/ezschedule/AppParametersTest.java
  src/test/java/ezschedule/logic/LogicManagerTest.java
  src/test/java/ezschedule/model/ModelManagerTest.java
Labels: type.Tests

#203 Draft PPP
  docs/team/lhy-hoyin.md
Labels: docs

#205 Add RecurFactor tests
  src/test/java/ezschedule/model/event/RecurFactorTest.java
Labels: type.Tests

#197 Update PPP
  docs/team/anthonynmh.md
Labels: docs

#193 Add RecurCommand tests
  src/main/java/ezschedule/logic/commands/RecurCommand.java
  src/test/java/ezschedule/logic/commands/CommandTestUtil.java
  src/test/java/ezschedule/logic/commands/RecurCommandTest.java
  src/test/java/ezschedule/logic/parser/RecurCommandParserTest.java
Labels: type.Tests

#207 Update PPP
  docs/team/jrmckh.md
Labels: docs

#208 Updated UG to be more comprehensive
  docs/UserGuide.md
Labels: docs

#209 change in clearRecent line
  src/main/java/ezschedule/logic/commands/DeleteCommand.java
Labels: bugfix

#210 Add Images to UG
  docs/UserGuide.md
  docs/images/add-command-result.png
  docs/images/calendar-gui.png
  docs/images/calendar.png
  docs/images/command-box.png
  docs/images/delete-command-result.png
  docs/images/edit-command-result.png
  docs/images/event-list.png
  docs/images/events-panel.png
  docs/images/gui.png
  docs/images/response-box-gui.png
  docs/images/response-box.png
  docs/images/upcoming-events-gui.png
  docs/images/upcoming-events.png
Labels: docs

#211 Update dg branch
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ParserClasses.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ParserClasses.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
  docs/img.png
Labels: docs

#212 Add Instructions for Manual Testing in DG
  docs/DeveloperGuide.md
Labels: docs

#215 Developer Guide: General improvements
  docs/DeveloperGuide.md
  docs/SettingUp.md
  docs/Testing.md
Labels: docs

#218 Fix bug that allows user to edit to existing event time
  src/main/java/ezschedule/logic/commands/EditCommand.java
  src/main/java/ezschedule/model/Model.java
  src/main/java/ezschedule/model/ModelManager.java
  src/main/java/ezschedule/model/Scheduler.java
  src/main/java/ezschedule/model/event/UniqueEventList.java
  src/test/java/ezschedule/logic/commands/AddCommandTest.java
  src/test/java/ezschedule/logic/commands/EditCommandTest.java
Labels: bugfix

#220 Feature delete
  src/main/java/ezschedule/commons/core/index/Index.java
  src/main/java/ezschedule/logic/commands/DeleteCommand.java
  src/main/java/ezschedule/logic/commands/EditCommand.java
  src/main/java/ezschedule/logic/commands/RecurCommand.java
  src/main/java/ezschedule/logic/commands/UndoCommand.java
  src/main/java/ezschedule/model/Model.java
  src/main/java/ezschedule/model/ModelManager.java
  src/test/java/ezschedule/logic/commands/AddCommandTest.java
  src/test/java/ezschedule/logic/commands/UndoCommandTest.java
  src/test/java/ezschedule/testutil/EventBuilder.java
Labels: bugfix

#216 Update user stories and use cases
  docs/DeveloperGuide.md
Labels: docs

#222 Developer + User Guide
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: docs

#221 Dg implementation branch
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddCommandActivityDiagram.puml
  docs/diagrams/DeleteCommandActivityDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/EditCommandActivityDiagram.puml
  docs/diagrams/FindCommandActivityDiagram.puml
  docs/diagrams/NextCommandActivityDiagram.puml
  docs/diagrams/RecurCommandActivityDiagram.puml
  docs/diagrams/UndoCommandActivityDiagram.puml
  docs/images/AddCommandActivityDiagram.png
  docs/images/DeleteCommandActivityDiagram.png
  docs/images/EditCommandActivityDiagram.png
  docs/images/FindCommandActivityDiagram.png
  docs/images/NextCommandActivityDiagram.png
  docs/images/RecurCommandActivityDiagram.png
  docs/images/UndoCommandActivityDiagram.png
  docs/img.png
Labels: docs

#219 Test undo
  src/main/java/ezschedule/commons/core/index/Index.java
  src/test/java/ezschedule/logic/commands/UndoCommandTest.java
  src/test/java/ezschedule/testutil/EventBuilder.java
Labels: type.Tests

#223 Add Planned Enhancements
  docs/DeveloperGuide.md
  docs/images/calendarBoxesNotFullyDisplayingName.png
  docs/images/calendarBoxesPlannedEnhancement.png
  docs/images/eventsPanelNotFullyDisplayingName.png
  docs/images/windowedScreenCutOff.png
Labels: docs

#224 Update/Complete PPP
  docs/UserGuide.md
  docs/images/johndoe.png
  docs/images/team/lhy-hoyin_Extract-UG-FAQ.png
  docs/images/team/lhy-hoyin_Extract-UG-Limitations.png
  docs/team/lhy-hoyin.md
Labels: docs

#225 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/AddCommandActivityDiagram.puml
  docs/diagrams/RecurCommandActivityDiagram.puml
  docs/diagrams/RecurCommandRecurringAddActivityDiagram.puml
  docs/images/AddCommandActivityDiagram.png
  docs/images/RecurCommandActivityDiagram.png
  docs/images/RecurCommandRecurringAddActivityDiagram.png
Labels: docs

#227 Add Find and Undo implementation documentation for DG
  docs/DeveloperGuide.md
  docs/diagrams/FindCommandActivityDiagram.puml
  docs/images/DeleteSequenceDiagram-new.png
  docs/images/DeleteSequenceDiagram.png
  src/main/java/ezschedule/logic/commands/AddCommand.java
  src/test/java/ezschedule/logic/commands/AddCommandTest.java
Labels: docs

#226 DG: Content for next command, delete command
  docs/DeveloperGuide.md
  docs/diagrams/NextCommandActivityDiagram.puml
  docs/diagrams/SortSequenceDiagram.puml
  docs/images/NextCommandActivityDiagram.png
  docs/images/SortSequenceDiagram.png
Labels: docs

#228 Final PPP update
  docs/team/jrmckh.md
Labels: docs

#229 DG: minor changes
  docs/DeveloperGuide.md
  docs/SettingUp.md
Labels: docs

#233 PPP: update contribution to DG
  docs/team/lhy-hoyin.md
Labels: docs

#232 Add break dg branch
  docs/DeveloperGuide.md
Labels: docs

#234 Update PPP
  docs/team/anthonynmh.md
Labels: docs

#235 Update PPP
  docs/team/bigheartsmallbrain.md
Labels: docs
