Repository AY2223S2-CS2103-W17-3/tp, pull requests merged in 2023-03, with the labels that each got.

#37 Update Ui mockup
  docs/images/Ui.png
Labels: documentation

#46 Set up with starting base code
  src/main/java/ezschedule/AppParameters.java
  src/main/java/ezschedule/Main.java
  src/main/java/ezschedule/MainApp.java
  src/main/java/ezschedule/commons/core/Config.java
  src/main/java/ezschedule/commons/core/GuiSettings.java
  src/main/java/ezschedule/commons/core/LogsCenter.java
  src/main/java/ezschedule/commons/core/Messages.java
  src/main/java/ezschedule/commons/core/Version.java
  src/main/java/ezschedule/commons/core/index/Index.java
  src/main/java/ezschedule/commons/exceptions/DataConversionException.java
  src/main/java/ezschedule/commons/exceptions/IllegalValueException.java
  src/main/java/ezschedule/commons/util/AppUtil.java
  src/main/java/ezschedule/commons/util/CollectionUtil.java
  src/main/java/ezschedule/commons/util/ConfigUtil.java
  src/main/java/ezschedule/commons/util/FileUtil.java
  src/main/java/ezschedule/commons/util/JsonUtil.java
  src/main/java/ezschedule/commons/util/StringUtil.java
  src/main/java/ezschedule/slots/Event.java
  src/main/java/ezschedule/slots/Slot.java
  src/main/java/ezschedule/slots/SlotScheduler.java
  src/main/java/ezschedule/slots/VenueBooking.java
  src/test/java/ezschedule/AppParametersTest.java
  src/test/java/ezschedule/MainAppTest.java
  src/test/java/ezschedule/commons/core/ConfigTest.java
  src/test/java/ezschedule/commons/core/VersionTest.java
  src/test/java/ezschedule/commons/core/index/IndexTest.java
  src/test/java/ezschedule/commons/util/AppUtilTest.java
  src/test/java/ezschedule/commons/util/CollectionUtilTest.java
  src/test/java/ezschedule/commons/util/ConfigUtilTest.java
  src/test/java/ezschedule/commons/util/FileUtilTest.java
  src/test/java/ezschedule/commons/util/StringUtilTest.java
  src/test/java/ezschedule/testutil/Assert.java
Labels: priority.High

#39 Update AboutUs
  docs/AboutUs.md
Labels: documentation

#40 Update PPP markdown file
  docs/AboutUs.md
  docs/team/bigheartsmallbrain.md
  docs/team/johndoe.md
Labels: documentation

#60 Fix issue that preventing module 'tP.main' from building
  src/main/java/seedu/address/model/event/Event.java
Labels: priority.High

#63 Update build.gradle for proper JAR release and improve code defense
  build.gradle
Labels: priority.Low

#66 Allow Event to be comparable
  src/main/java/ezschedule/model/event/Date.java
  src/main/java/ezschedule/model/event/Event.java
  src/main/java/ezschedule/model/event/Time.java
Labels: type.Enhancement

#62 Fix title of AboutUs.md
  docs/AboutUs.md
  docs/images/lhy-hoyin.png
Labels: documentation, priority.Low

#69 Develop auto mark done
  src/main/java/ezschedule/model/event/Event.java
  src/main/java/ezschedule/model/event/Time.java
  src/main/java/ezschedule/ui/EventCard.java
  src/main/resources/view/EventListCard.fxml
  src/test/java/ezschedule/model/event/TimeTest.java
Labels: type.Enhancement

#77 Update DG up to "Common classes"
  docs/DeveloperGuide.md
Labels: documentation

#78 Add a draft implementation of calender view UI to DG
  docs/AboutUs.md
  docs/DeveloperGuide.md
Labels: documentation

#79 Update DG
  docs/DeveloperGuide.md
Labels: documentation

#68 Sort Events feature
  src/main/java/ezschedule/logic/commands/SortCommand.java
  src/main/java/ezschedule/logic/parser/SchedulerParser.java
  src/main/java/ezschedule/model/Model.java
  src/main/java/ezschedule/model/ModelManager.java
  src/main/java/ezschedule/model/Scheduler.java
  src/main/java/ezschedule/model/event/UniqueEventList.java
  src/main/java/ezschedule/ui/UiManager.java
  src/test/java/ezschedule/logic/commands/AddCommandTest.java
  src/test/java/ezschedule/logic/commands/SortCommandTest.java
  src/test/java/ezschedule/logic/parser/SchedulerParserTest.java
Labels: type.Feature

#81 DeveloperGuide: Sort Event documentation
  docs/DeveloperGuide.md
Labels: documentation

#83 Enhance events duplicate checker to check all fields
  src/main/java/ezschedule/model/event/Event.java
  src/test/java/ezschedule/model/SchedulerTest.java
  src/test/java/ezschedule/model/event/EventTest.java
  src/test/java/ezschedule/model/event/UniqueEventListTest.java
Labels: bug

#76 Prevents event from being added if the date and time clashes with an existing event
  src/main/java/ezschedule/logic/commands/AddCommand.java
  src/main/java/ezschedule/model/Model.java
  src/main/java/ezschedule/model/ModelManager.java
  src/main/java/ezschedule/model/Scheduler.java
  src/main/java/ezschedule/model/event/Event.java
  src/main/java/ezschedule/model/event/Time.java
  src/main/java/ezschedule/model/event/UniqueEventList.java
  src/test/java/ezschedule/logic/commands/AddCommandIntegrationTest.java
  src/test/java/ezschedule/logic/commands/AddCommandTest.java
  src/test/java/ezschedule/testutil/EventBuilder.java
Labels: type.Feature

#86 Merge branch-RecurCommand
  src/main/java/ezschedule/logic/commands/AddCommand.java
  src/main/java/ezschedule/logic/commands/EditCommand.java
  src/main/java/ezschedule/logic/commands/RecurCommand.java
  src/main/java/ezschedule/logic/parser/CliSyntax.java
  src/main/java/ezschedule/logic/parser/ParserUtil.java
  src/main/java/ezschedule/logic/parser/RecurCommandParser.java
  src/main/java/ezschedule/logic/parser/SchedulerParser.java
  src/main/java/ezschedule/model/event/Date.java
  src/main/java/ezschedule/model/event/RecurFactor.java
  src/main/java/ezschedule/model/event/UniqueEventList.java
Labels: type.Enhancement, priority.Medium

#88 Add WEEK to RecurCommand
  src/main/java/ezschedule/logic/commands/RecurCommand.java
  src/main/java/ezschedule/model/event/RecurFactor.java
Labels: type.Enhancement

#91 Enhance Sort to trigger automatically
  src/main/java/ezschedule/logic/commands/SortCommand.java
  src/main/java/ezschedule/logic/parser/SchedulerParser.java
  src/main/java/ezschedule/model/Model.java
  src/main/java/ezschedule/model/ModelManager.java
  src/main/java/ezschedule/model/Scheduler.java
  src/main/java/ezschedule/model/event/UniqueEventList.java
  src/test/java/ezschedule/logic/commands/AddCommandTest.java
  src/test/java/ezschedule/logic/commands/SortCommandTest.java
  src/test/java/ezschedule/logic/parser/SchedulerParserTest.java
Labels: type.Enhancement, priority.High

#80 Add task dependency when generating jar
  build.gradle
Labels: priority.Low

#92 Add find by date feature
  src/main/java/ezschedule/logic/commands/FindCommand.java
  src/main/java/ezschedule/logic/parser/FindCommandParser.java
  src/main/java/ezschedule/model/event/EventMatchesDatePredicate.java
  src/main/java/ezschedule/model/event/EventMatchesKeywordsAndDatePredicate.java
  src/test/java/ezschedule/logic/commands/FindCommandTest.java
  src/test/java/ezschedule/logic/parser/FindCommandParserTest.java
  src/test/java/ezschedule/logic/parser/SchedulerParserTest.java
  src/test/java/ezschedule/testutil/EventUtil.java
  src/test/java/ezschedule/testutil/FindEventDescriptorBuilder.java
Labels: type.Enhancement

#93 New Feature: ShowNext Command
  src/main/java/ezschedule/logic/Logic.java
  src/main/java/ezschedule/logic/LogicManager.java
  src/main/java/ezschedule/logic/commands/ShowNextCommand.java
  src/main/java/ezschedule/logic/parser/SchedulerParser.java
  src/main/java/ezschedule/logic/parser/ShowNextCommandParser.java
  src/main/java/ezschedule/model/Model.java
  src/main/java/ezschedule/model/ModelManager.java
  src/main/java/ezschedule/model/Scheduler.java
  src/main/java/ezschedule/model/event/Event.java
  src/main/java/ezschedule/model/event/EventContainsKeywordsPredicate.java
  src/main/java/ezschedule/model/event/UniqueEventList.java
  src/main/java/ezschedule/model/event/UpcomingEventPredicate.java
  src/test/java/ezschedule/logic/commands/AddCommandTest.java
  src/test/java/ezschedule/logic/parser/SchedulerParserTest.java
Labels: priority.High, type.Feature

#97 User Guide
  docs/AboutUs.md
  docs/UserGuide.md
  docs/index.md
Labels: docs

#98 Beautified UI
  src/main/java/ezschedule/MainApp.java
  src/main/java/ezschedule/model/event/Event.java
  src/main/java/ezschedule/ui/CalendarBox.java
  src/main/java/ezschedule/ui/EventCard.java
  src/main/java/ezschedule/ui/EventListPanel.java
  src/main/java/ezschedule/ui/ShowNextCard.java
  src/main/java/ezschedule/ui/ShowNextPanel.java
  src/main/java/ezschedule/ui/UiManager.java
  src/main/resources/images/check-mark.png
  src/main/resources/images/scheduler.png
  src/main/resources/view/Calendar.fxml
  src/main/resources/view/CalendarBox.fxml
  src/main/resources/view/DarkGreenTheme.css
  src/main/resources/view/EventListCard.fxml
  src/main/resources/view/EventListPanel.fxml
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/ShowNextCard.fxml
  src/main/resources/view/ShowNextPanel.fxml
  src/test/java/ezschedule/model/event/EventTest.java
Labels: type.Enhancement

#99 Highlight calender event on find command
  src/main/java/ezschedule/logic/Logic.java
  src/main/java/ezschedule/logic/LogicManager.java
  src/main/java/ezschedule/logic/commands/FindCommand.java
  src/main/java/ezschedule/logic/commands/ListCommand.java
  src/main/java/ezschedule/model/Model.java
  src/main/java/ezschedule/model/ModelManager.java
  src/main/java/ezschedule/ui/Calendar.java
  src/main/java/ezschedule/ui/CalendarBox.java
  src/main/java/ezschedule/ui/MainWindow.java
  src/test/java/ezschedule/logic/commands/AddCommandTest.java
Labels: type.Enhancement

#103 Update edit, find, delete, and GUI in UG
  docs/UserGuide.md
  docs/img.png
  docs/img_1.png
  src/main/resources/images/calendar.png
  src/main/resources/images/command-box.png
  src/main/resources/images/event-list.png
  src/main/resources/images/response-box.png
  src/main/resources/images/upcoming-events.png
Labels: docs

#104 Update Ui.png
  docs/images/Ui.png
  docs/img.png
  docs/img_1.png
  docs/index.md
Labels: docs

#90 Add undo feature
  src/main/java/ezschedule/logic/commands/AddCommand.java
  src/main/java/ezschedule/logic/commands/ClearCommand.java
  src/main/java/ezschedule/logic/commands/Command.java
  src/main/java/ezschedule/logic/commands/DeleteCommand.java
  src/main/java/ezschedule/logic/commands/EditCommand.java
  src/main/java/ezschedule/logic/commands/ExitCommand.java
  src/main/java/ezschedule/logic/commands/FindCommand.java
  src/main/java/ezschedule/logic/commands/HelpCommand.java
  src/main/java/ezschedule/logic/commands/ListCommand.java
  src/main/java/ezschedule/logic/commands/RecurCommand.java
  src/main/java/ezschedule/logic/commands/ShowNextCommand.java
  src/main/java/ezschedule/logic/commands/UndoCommand.java
  src/main/java/ezschedule/logic/parser/SchedulerParser.java
  src/main/java/ezschedule/model/Model.java
  src/main/java/ezschedule/model/ModelManager.java
  src/test/java/ezschedule/logic/commands/AddCommandTest.java
Labels: type.Feature

#106 Fix bug from previous push
  src/main/java/ezschedule/logic/commands/RecurCommand.java
  src/main/java/ezschedule/logic/commands/UndoCommand.java
  src/main/java/ezschedule/model/ModelManager.java
  src/test/java/ezschedule/logic/commands/AddCommandTest.java
Labels: type.Enhancement, priority.High

#107 Update UG for undo feature
  docs/UserGuide.md
Labels: docs

#109 Fix broken image links in UG
  docs/UserGuide.md
Labels: bug, docs

#111 Fix exception catching for Recur
  src/main/java/ezschedule/logic/commands/RecurCommand.java
  src/main/java/ezschedule/logic/parser/RecurCommandParser.java
Labels: bugfix

#116 Improve minor hyperlink issues in UG
  docs/UserGuide.md
  docs/images/calendar.png
  docs/images/command-box.png
  docs/images/event-list.png
  docs/images/response-box.png
  docs/images/upcoming-events.png
Labels: docs
